/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useMotionValue, useSpring } from 'framer-motion'

export function Astronaut(props) {
    
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/bionic_boy_super_hero_animated.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if (animations.length>0) {
        actions[animations[0].name].play();
        }
    }, [animations, actions]);

    const yPosition = useMotionValue(5);
    const ySpring = useSpring(yPosition, {damping:30});
    useEffect(() => {
      ySpring.set(-1.2);
    }, []);
    useFrame(() => {
      group.current.position.y = ySpring.get();
    })
  return (
    <group ref={group} 
        {...props} 
        dispose={null}
        rotation={[-2.5,0.3,0.2]} 
        scale={props.scale || 1.3}
        position={props.position || [2.0, -2.8, 0]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model">
          <group
            name="10e726b128ed4626885caaee3a7eb39efbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature">
                  <group name="Object_5">
                    <primitive object={nodes.mixamorigHips_01} />
                    <group name="Object_84" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_86" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_88" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                      <skinnedMesh
                        name="Object_89"
                        geometry={nodes.Object_89.geometry}
                        material={materials.teeth}
                        skeleton={nodes.Object_89.skeleton}
                        morphTargetDictionary={nodes.Object_89.morphTargetDictionary}
                        morphTargetInfluences={nodes.Object_89.morphTargetInfluences}
                      />
                    </group>
                    <group name="Object_90" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                      <skinnedMesh
                        name="Object_91"
                        geometry={nodes.Object_91.geometry}
                        material={materials.eye_left}
                        skeleton={nodes.Object_91.skeleton}
                        morphTargetDictionary={nodes.Object_91.morphTargetDictionary}
                        morphTargetInfluences={nodes.Object_91.morphTargetInfluences}
                      />
                    </group>
                    <group name="Object_92" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_94" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_96" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                      <skinnedMesh
                        name="Object_97"
                        geometry={nodes.Object_97.geometry}
                        material={materials.head}
                        skeleton={nodes.Object_97.skeleton}
                        morphTargetDictionary={nodes.Object_97.morphTargetDictionary}
                        morphTargetInfluences={nodes.Object_97.morphTargetInfluences}
                      />
                    </group>
                    <group name="Object_98" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_100" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                      <skinnedMesh
                        name="Object_101"
                        geometry={nodes.Object_101.geometry}
                        material={materials.eye_left}
                        skeleton={nodes.Object_101.skeleton}
                        morphTargetDictionary={nodes.Object_101.morphTargetDictionary}
                        morphTargetInfluences={nodes.Object_101.morphTargetInfluences}
                      />
                    </group>
                    <group name="Object_102" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  </group>
                </group>
                <group name="body" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="bottom" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="teeth" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="eye_left" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="hair" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="shoes" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="head" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="top" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="eye_right" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="glasses" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
          <skinnedMesh
            name="Object_85"
            geometry={nodes.Object_85.geometry}
            material={materials.body}
            skeleton={nodes.Object_85.skeleton}
          />
          <skinnedMesh
            name="Object_87"
            geometry={nodes.Object_87.geometry}
            material={materials.bottom}
            skeleton={nodes.Object_87.skeleton}
          />
          <skinnedMesh
            name="Object_93"
            geometry={nodes.Object_93.geometry}
            material={materials.hair}
            skeleton={nodes.Object_93.skeleton}
          />
          <skinnedMesh
            name="Object_95"
            geometry={nodes.Object_95.geometry}
            material={materials.shoes}
            skeleton={nodes.Object_95.skeleton}
          />
          <skinnedMesh
            name="Object_99"
            geometry={nodes.Object_99.geometry}
            material={materials.material}
            skeleton={nodes.Object_99.skeleton}
          />
          <skinnedMesh
            name="Object_103"
            geometry={nodes.Object_103.geometry}
            material={materials.glasses}
            skeleton={nodes.Object_103.skeleton}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bionic_boy_super_hero_animated.glb')
